spring:
  application:
    name: temporal-java-shutdown
  profiles:
    active: ${SPRING_PROFILE:default}
  temporal:
    namespace: ${TEMPORAL_NAMESPACE:default}
    connection:
      target: ${TEMPORAL_ADDRESS:127.0.0.1:7233}
    workers:
      - name: shutdown-worker
        task-queue: shutdown-task-queue-${HOSTNAME}
    workersAutoDiscovery:
      packages:
        - com.example.workflows
        - com.example.activities

#logging:
#  pattern:
#    console: "%d{HH:mm:ss.SSS} {%X{WorkflowId} %X{ActivityId}} [%thread] %-5level %logger{36} - %msg %n"
#    console: "%d{HH:mm:ss.SSS} {%mdc} [%thread] %-5level %logger{36} - %msg %n"
